### ISSUE TITLE
CatchPokemon is working but returns error..

### ISSUE THREAD

**Issue by stoffern** [stoffern/pokemongo-api#23]

**Comment by gallexme** [comment]
not always returning error:
[i] Received OK: EncounterResponse
[i] Received OK: CatchPokemonResponse
{ encounterResult: { EncounterResponse: { wild_pokemon: [Object], background: 0, status: 1 } },
  catchPokemonResult: { CatchPokemonResponse: { status: 3, miss_percent: 0, capture_award: null } } }

**Comment by stoffern** [comment]
Thisone is quite wierd.
Could it be any banned pokemons that your are not supposed to catch?

@maxnowack the best thing to do is to debug the response before it is sendt to the decoder.
https://github.com/stoffern/pokemongo-api/blob/master/src/API.js#L32

**Comment by maxnowack** [comment]
I've played a bit around with CatchPokemon. It seems, that a pokemon got caught if the response return an error. If no error occurs, the throw was not successful

**Comment by stoffern** [comment]
@maxnowack what version are you using?

**Comment by maxnowack** [comment]
0.1.7

**Comment by stoffern** [comment]
try updating

**Comment by stoffern** [comment]
@maxnowack did it work after update?

**Comment by maxnowack** [comment]
No, I'm still getting an error ...

**Comment by jimmywarting** [comment]
I got the error from Rattata. And Rattata is **not** banned

**Comment by jimmywarting** [comment]
the other api have something like 
['Unexpected error', 'Successful catch', 'Catch Escape', 'Catch Flee', 'Missed Catch'];

[ref](https://github.com/Armax/Pokemon-GO-node-api/blob/master/example.js#L116)

if the result is missed, then we should try catching it again?

**Comment by InsOpDe** [comment]
Im getting
`[Error: Illegal wire type for field Message.Field .POGOProtos.Data.Capture.CaptureAward.activity_type: 2 (0 expected)]`

**Comment by stoffern** [comment]
@jimmywarting you cant read the response.status before its decoded.
And the throw error is from having problem with decoding.
I am almost 100% shure that this is a server stability issue and not a problem with the code.

Should be log a warn on response error, and try sending a request again instead of throwing a error?

@InsOpDe can you share your code?

**Comment by InsOpDe** [comment]
well im reprogramming this project in es5 (for various reasons) so it may be possible that there are errors in my code. but I think it is rather a problem with the *.proto files since the error above implies it.

```
var Request = function(requests, userObj, callback){
        _request(requests, userObj, function(response){
            try {
                //we have response (returns = response we want.. now lets parse it)
                var respt = {};
                requests.map( function(req,key){
                    //setFileName
                    var ResponseType = _resolveProtoFilename(req.request);
                    ResponseType = ResponseType + 'Response';
                    var Responses = POGOProtos.Networking.Responses;
                    try {
                        respt[ResponseType] = Responses[ResponseType].decode(response.returns[key]);
                        //console.log('[i] Received OK: '+ResponseType)
                    } catch(error) {
                        console.log('[!] Response error!');
                        console.log(error); // <- Im getting it here
                    }
                });
                callback(respt);
            } catch(e) {
                console.log("Request");
                console.log(e);
            }
        })
    };
```

**Comment by stoffern** [comment]
@InsOpDe that looks good to me. why not just compile it to es5 with babel if so?

To me it looks like the protobuf is trying to parse a request you have and it errors when trying to parse data in that request binded in `POGOProtos.Data.Capture.CaptureAward.activity_type`
it says that your type data for activity_type is invalid. 
What requst is causing the error? I would try to change the type or deactivate it?

**Comment by InsOpDe** [comment]
@stoffern im coding on windows and running it on a Linux vm (since i couldnt get s2geometry running on windows) so I needed to modify the require-paths to the nodemodules - and since im not much into es6 (and its import-funcitonality) or transpiling it with babel to es5,  id rather stay on es5 for now :D 

yes that much i figured out, too - i see that this field is referenced to the enum activityType in the ActivityType.proto . But i cannot figure out what kind of type is used there - so I cannot change it

**Comment by stoffern** [comment]
@InsOpDe we are running the lastest `s2geometry-node` it is confirmed to work on windows 8, windows 10, linux and mac..
Altho on windows you need `Visaul Studio 2015 Community` edition to compile..

our npm package is a compiled ES5 so you can just write ES5 on top of the NPM..

**Comment by InsOpDe** [comment]
@stoffern well thank you for your insight - I tried everything i am capable of, but now Im chosing this solution. If you think that this error response may relate to my setup you may ignore it and I have to figure it out myself, if not, then maybe im not the only one with this problem

**Comment by stoffern** [comment]
CatchPokemon is working fine when the server is stable.
This error has to do with some of your code as far as i can see..

closing this issue as this is working, and server instability usually triggers error..

**Comment by gallexme** [comment]
maybe we should watch this issue as it
happens for me now with all pokemons
Error: Illegal wire type for field Message.Field .POGOProtos.Data.Capture.CaptureAward.activity_type: 2 (0 expected)

**Comment by jimmywarting** [comment]
I get that sometimes, not always maybe 50/50

**Comment by stoffern** [comment]
Can someone provide a dump of the response when it fails?
so we can compare them and see what it is?
I would guess it is something about a optional or extra parameter in the Protos

**Comment by jimmywarting** [comment]
Maybe this is solved with the new proto update

**Comment by DaVarga** [comment]
Error still exists...
´´´
Error: Illegal wire type for field Message.Field .POGOProtos.Data.Capture.CaptureAward.activity_type: 2 (0 expected)
    at Error (native)
    at ProtoBuf.Reflect.FieldPrototype.decode (.../node_modules/protobufjs/dist/protobuf.js:3679:23)
    at ProtoBuf.Reflect.MessagePrototype.decode (.../node_modules/protobufjs/dist/protobuf.js:3233:48)
    at ProtoBuf.Reflect.ElementPrototype.decode (.../node_modules/protobufjs/dist/protobuf.js:2185:46)
    at ProtoBuf.Reflect.FieldPrototype.decode (.../node_modules/protobufjs/dist/protobuf.js:3727:33)
    at ProtoBuf.Reflect.MessagePrototype.decode (.../node_modules/protobufjs/dist/protobuf.js:3238:45)
    at Function.Message.decode (.../node_modules/protobufjs/dist/protobuf.js:2933:37)
    at .../node_modules/pokemongo-api/dist/API.js:74:67
    at Array.map (native)
    at Connection._callee$ (.../node_modules/pokemongo-api/dist/API.js:68:26)

´´´

**Comment by stoffern** [comment]
Finally now it should work properly. 65f7956bb02e0da9c16b8e178da9dd2502e2afe0
